### ISSUE TITLE
Doesn't works.

### ISSUE THREAD

**Issue by juario17** [dgsasha/qualia-gtk-theme-snap#1]
![Screenshot from 2022-12-19 10-27-29](https://user-images.githubusercontent.com/9750729/208460907-91b089b7-a83d-4d44-94b2-bcca0d129e8e.png)

![Screenshot from 2022-12-19 10-28-37](https://user-images.githubusercontent.com/9750729/208461047-966d2b31-3b33-4df9-9b94-6e0cd14675e7.png)

![Screenshot from 2022-12-19 10-29-49](https://user-images.githubusercontent.com/9750729/208461268-88a17145-a310-4549-b29a-b42f3e55c22f.png)

**Comment by dgsasha** [comment]
This snap must be used with [qualia-gtk-theme](https://github.com/dgsasha/qualia-gtk-theme). It only adds support for snap apps, it does not install a theme that can be used system wide. Just run the install script in the link I provided and it will handle setting up the snap for you.

**Comment by dgsasha** [comment]
I apologize for not making this more clear, I updated the snap listing page to mention this requirement. Thanks for opening the issue and making me aware of this.
